name: NekoNYume
version: '${version}'

main: mizukichou.nekonyume.NekoNYume
api-version: '26.2'
load: POSTWORLD

commands:
  nekoyume:
    description: Neko n' Yume main command
    usage: /nekoyume <help|claim|cat|rename|summon|mode>
    aliases:
      - ny

  nekoyumeadmin:
    description: Neko n' Yume admin commands
    usage: /nekoyumeadmin <meowdan|reload>
    aliases:
      - nyadmin
      - nya
    permission: nekoyume.admin


permissions:
  nekoyume.admin:
    description: Neko n' Yume administrator permission
    default: op
